apiVersion: v1
kind: ConfigMap
metadata:
  name: codementor-ai-config
  namespace: codementor-ai
data:
  NODE_ENV: "production"
  PORT: "3001"
  CLIENT_URL: "https://codementor-ai.com"
  OPENAI_MODEL: "gpt-4"
  OPENAI_MAX_TOKENS: "2000"
  OPENAI_TEMPERATURE: "0.7"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  MAX_FILE_SIZE: "10485760"
  UPLOAD_DIR: "/app/uploads"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  LOG_LEVEL: "info"
  LOG_FILE: "/app/logs/app.log"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: codementor-ai
data:
  POSTGRES_DB: "codementor_ai"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: codementor-ai
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 256mb
    maxmemory-policy allkeys-lru